//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProductos
    {
        public short Tipo { get; set; }
        public short Producto { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionIngles { get; set; }
        public short Consecutivo { get; set; }
        public string CodCaades { get; set; }
        public short CtaEmb { get; set; }
        public string SubCtaGral { get; set; }
        public short ConsecClasif { get; set; }
        public string Temperatura { get; set; }
        public string NomBotanico { get; set; }
        public string CodTrazabilidad { get; set; }
        public bool organico { get; set; }
        public Nullable<bool> Pedido { get; set; }
        public string Abreviacion { get; set; }
        public bool Propia { get; set; }
        public Nullable<short> Contrato { get; set; }
        public string Grupo { get; set; }
    }
}
