//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatTiposProd
    {
        public short Tipo { get; set; }
        public string Descripcion { get; set; }
        public byte HPreEnfria { get; set; }
        public byte MPreEnfria { get; set; }
        public short Consecutivo { get; set; }
        public bool SeparaCto { get; set; }
        public string DescIngles { get; set; }
        public string DescripcionAd { get; set; }
        public string FraccionArancelaria { get; set; }
        public string CodigoSAT { get; set; }
        public string Cod_UniMed { get; set; }
        public string Cod_UniMedProd { get; set; }
        public string CodigoSATProd { get; set; }
    }
}
