//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeasonSun1213Entities5 : DbContext
    {
        public SeasonSun1213Entities5()
            : base("name=SeasonSun1213Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatSemanas> CatSemanas { get; set; }
        public virtual DbSet<Estimacion_Berries> Estimacion_Berries { get; set; }
        public virtual DbSet<UV_ProdRecepcion> UV_ProdRecepcion { get; set; }
    }
}
