//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeasonSun1213Entities16 : DbContext
    {
        public SeasonSun1213Entities16()
            : base("name=SeasonSun1213Entities16")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatAcopios> CatAcopios { get; set; }
        public virtual DbSet<CatProductos> CatProductos { get; set; }
        public virtual DbSet<CatSemanas> CatSemanas { get; set; }
        public virtual DbSet<CatTiposProd> CatTiposProd { get; set; }
        public virtual DbSet<ProdAgenteCat> ProdAgenteCat { get; set; }
        public virtual DbSet<ProdCamposCat> ProdCamposCat { get; set; }
        public virtual DbSet<ProdProductoresCat> ProdProductoresCat { get; set; }
        public virtual DbSet<SIPGVisitas> SIPGVisitas { get; set; }
        public virtual DbSet<SIPGComentarios> SIPGComentarios { get; set; }
        public virtual DbSet<ProdVisitasCab> ProdVisitasCab { get; set; }
        public virtual DbSet<SIPGProyeccion> SIPGProyeccion { get; set; }
    }
}
