//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeasonSun1213Entities15 : DbContext
    {
        public SeasonSun1213Entities15()
            : base("name=SeasonSun1213Entities15")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatLocalidades> CatLocalidades { get; set; }
        public virtual DbSet<CatProductos> CatProductos { get; set; }
        public virtual DbSet<CatTiposProd> CatTiposProd { get; set; }
        public virtual DbSet<ProdAgenteCat> ProdAgenteCat { get; set; }
        public virtual DbSet<ProdAnalisis_Residuo> ProdAnalisis_Residuo { get; set; }
        public virtual DbSet<ProdCalidadMuestreo> ProdCalidadMuestreo { get; set; }
        public virtual DbSet<ProdCamposCat> ProdCamposCat { get; set; }
        public virtual DbSet<ProdMuestreo> ProdMuestreo { get; set; }
        public virtual DbSet<ProdMuestreoSector> ProdMuestreoSector { get; set; }
        public virtual DbSet<ProdProductoresCat> ProdProductoresCat { get; set; }
        public virtual DbSet<SIPGUsuarios> SIPGUsuarios { get; set; }
        public virtual DbSet<ProdZonasRastreoCat> ProdZonasRastreoCat { get; set; }
    }
}
