//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdZonasRastreoCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdZonasRastreoCat()
        {
            this.ProdCamposCat = new HashSet<ProdCamposCat>();
        }
    
        public short IdZona { get; set; }
        public string Codigo { get; set; }
        public string DescZona { get; set; }
        public Nullable<bool> Pedido { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public Nullable<int> SRegion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdCamposCat> ProdCamposCat { get; set; }
    }
}
