//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdMuestreo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdMuestreo()
        {
            this.ProdCalidadMuestreo = new HashSet<ProdCalidadMuestreo>();
        }
    
        public int Id { get; set; }
        public short Cod_Empresa { get; set; }
        public string Cod_Prod { get; set; }
        public short Cod_Campo { get; set; }
        public Nullable<System.DateTime> Fecha_solicitud { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> Inicio_cosecha { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public string Liberacion { get; set; }
        public string Tarjeta { get; set; }
        public Nullable<System.DateTime> Fecha_ejecucion { get; set; }
        public Nullable<int> IdSector { get; set; }
        public Nullable<short> IdAgenI { get; set; }
        public Nullable<short> IdAgen_Tarjeta { get; set; }
        public string Liberar_Tarjeta { get; set; }
        public string Compras_Oportunidad { get; set; }
        public virtual ProdAgenteCat ProdAgenteCat { get; set; }
        public virtual ProdAgenteCat ProdAgenteCat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdCalidadMuestreo> ProdCalidadMuestreo { get; set; }
        public virtual ProdCamposCat ProdCamposCat { get; set; }
        public virtual ProdCamposCat ProdCamposCat1 { get; set; }
        public virtual ProdMuestreoSector ProdMuestreoSector { get; set; }
        public virtual ProdProductoresCat ProdProductoresCat { get; set; }
    }
}
