//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdVisitasCab
    {
        public int IdVisita { get; set; }
        public short IdAgen { get; set; }
        public string Cod_prod { get; set; }
        public short Cod_Campo { get; set; }
        public Nullable<short> IdSector { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estatus { get; set; }
        public string Comentarios { get; set; }
        public string Atendio { get; set; }
        public string UidApp { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
        public string TipoVisita { get; set; }
    }
}
