//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdCalidadMuestreo
    {
        public int Id { get; set; }
        public string Estatus { get; set; }
        public string Incidencia { get; set; }
        public string Propuesta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public Nullable<int> Id_Muestreo { get; set; }
    
        public virtual ProdMuestreo ProdMuestreo { get; set; }
    }
}
