//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdMuestreoSector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProdMuestreoSector()
        {
            this.ProdAnalisis_Residuo = new HashSet<ProdAnalisis_Residuo>();
            this.ProdMuestreo = new HashSet<ProdMuestreo>();
        }
    
        public int id { get; set; }
        public string Cod_Prod { get; set; }
        public Nullable<short> Cod_Campo { get; set; }
        public Nullable<short> Sector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdAnalisis_Residuo> ProdAnalisis_Residuo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdMuestreo> ProdMuestreo { get; set; }
    }
}
