//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdAnalisis_Residuo
    {
        public int Id { get; set; }
        public string Cod_Prod { get; set; }
        public short Cod_Campo { get; set; }
        public string CodZona { get; set; }
        public Nullable<System.DateTime> Fecha_envio { get; set; }
        public Nullable<System.DateTime> Fecha_entrega { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Num_analisis { get; set; }
        public string Laboratorio { get; set; }
        public string Comentarios { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Muestreo { get; set; }
        public Nullable<System.DateTime> LiberacionUSA { get; set; }
        public Nullable<System.DateTime> LiberacionEU { get; set; }
        public Nullable<int> IdSector { get; set; }
        public short Cod_Empresa { get; set; }
        public string Folio { get; set; }
        public string Temporada { get; set; }
        public string Traza { get; set; }
    
        public virtual ProdMuestreoSector ProdMuestreoSector { get; set; }
    }
}
