//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPGProyeccion
    {
        public int Id { get; set; }
        public string Estado { get; set; }
        public string Estado_M { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public string Cod_Prod { get; set; }
        public Nullable<short> Cod_Campo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Num_corte { get; set; }
        public Nullable<int> Sector { get; set; }
        public Nullable<double> Ha { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string Producto { get; set; }
        public string Numplantas_xha { get; set; }
        public string Manejo { get; set; }
        public string Tipo_plantacion { get; set; }
        public Nullable<System.DateTime> Fecha_plantacion { get; set; }
        public Nullable<System.DateTime> Fecha_poda { get; set; }
        public Nullable<System.DateTime> Fecha_defoliacion { get; set; }
        public Nullable<System.DateTime> Fecha_corte1 { get; set; }
        public Nullable<System.DateTime> Fecha_redefoliacion { get; set; }
        public Nullable<System.DateTime> Fecha_corte2 { get; set; }
        public Nullable<int> Sem1 { get; set; }
        public string Plantacion { get; set; }
        public Nullable<int> Sem2 { get; set; }
        public Nullable<double> Caja1 { get; set; }
        public Nullable<double> Caja2 { get; set; }
        public string Estructura { get; set; }
        public string Tipo_certificacion { get; set; }
        public string Tesco { get; set; }
        public string Edad_planta { get; set; }
        public string Tipo_plantacion2 { get; set; }
        public Nullable<System.DateTime> Fecha_podamediacaña { get; set; }
        public string RendxKg { get; set; }
        public string RendxHa { get; set; }
        public Nullable<double> TotalCajas { get; set; }
        public string Temporada { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<short> Zona { get; set; }
        public Nullable<short> Acopio { get; set; }
        public string Just_Estado { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<double> C27 { get; set; }
        public Nullable<double> C28 { get; set; }
        public Nullable<double> C29 { get; set; }
        public Nullable<double> C30 { get; set; }
        public Nullable<double> C31 { get; set; }
        public Nullable<double> C32 { get; set; }
        public Nullable<double> C33 { get; set; }
        public Nullable<double> C34 { get; set; }
        public Nullable<double> C35 { get; set; }
        public Nullable<double> C36 { get; set; }
        public Nullable<double> C37 { get; set; }
        public Nullable<double> C38 { get; set; }
        public Nullable<double> C39 { get; set; }
        public Nullable<double> C40 { get; set; }
        public Nullable<double> C41 { get; set; }
        public Nullable<double> C42 { get; set; }
        public Nullable<double> C43 { get; set; }
        public Nullable<double> C44 { get; set; }
        public Nullable<double> C45 { get; set; }
        public Nullable<double> C46 { get; set; }
        public Nullable<double> C47 { get; set; }
        public Nullable<double> C48 { get; set; }
        public Nullable<double> C49 { get; set; }
        public Nullable<double> C50 { get; set; }
        public Nullable<double> C51 { get; set; }
        public Nullable<double> C52 { get; set; }
        public Nullable<double> C53 { get; set; }
        public Nullable<double> C1 { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<double> C3 { get; set; }
        public Nullable<double> C4 { get; set; }
        public Nullable<double> C5 { get; set; }
        public Nullable<double> C6 { get; set; }
        public Nullable<double> C7 { get; set; }
        public Nullable<double> C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public Nullable<double> C10 { get; set; }
        public Nullable<double> C11 { get; set; }
        public Nullable<double> C12 { get; set; }
        public Nullable<double> C13 { get; set; }
        public Nullable<double> C14 { get; set; }
        public Nullable<double> C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public Nullable<double> C17 { get; set; }
        public Nullable<double> C18 { get; set; }
        public Nullable<double> C19 { get; set; }
        public Nullable<double> C20 { get; set; }
        public Nullable<double> C21 { get; set; }
        public Nullable<double> C22 { get; set; }
        public Nullable<double> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public Nullable<double> C25 { get; set; }
        public Nullable<double> C26 { get; set; }
    }
}
