//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPGComentarios
    {
        public int Id { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cod_prod { get; set; }
        public string Comentario { get; set; }
    }
}
