//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Indicadores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPGUsuarios
    {
        public string Nombre { get; set; }
        public string Clave { get; set; }
        public string Completo { get; set; }
        public string correo { get; set; }
        public Nullable<short> IdAgen { get; set; }
        public Nullable<short> IdRegion { get; set; }
        public string Tipo { get; set; }
        public int Id { get; set; }
    }
}
